version: "2"

services:
  app:
    build: ./
    links:
      - database
    ports:
      - "8083:3305"
  database:
    image: mysql:latest
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Annesql
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
