-- Generated by Oracle SQL Developer Data Modeler 17.4.0.355.2121
--   at:        2020-06-04 11:29:38 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE variant (
    variant_id            VARCHAR(10) NOT NULL,
    chromosome             VARCHAR(10),
    position               INTEGER,
    reference              VARCHAR(10),
    alternative            VARCHAR(10),
    variant_type			VARCHAR(10),
    cancer_alt_allele_frequency			FLOAT
    -- alt_allele_frequency   FLOAT
);

ALTER TABLE variant ADD CONSTRAINT variant_pk PRIMARY KEY ( mutation_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             1
-- CREATE INDEX                             0
-- ALTER TABLE                              1
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
